# Generated by Django 5.0.6 on 2024-05-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_like_post_alter_like_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
