# Generated by Django 4.1 on 2024-05-31 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
